package br.com.srcsoftware.topomanager.constantes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;

public class NumerosBase {

	public static ArrayList< LinkedHashSet<Integer>> negativosDe2 = new ArrayList<>();
	public static ArrayList< LinkedHashSet<Integer>> negativosDe6 = new ArrayList<>();
	
	static {
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	3	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	6	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	3	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	6	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	4	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	5	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	6	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	6	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	6	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	7	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	8	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	9	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	10	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	9	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	11	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	10	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	12	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	13	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	12	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	14	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	13	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	15	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	14	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	16	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	15	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	17	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	16	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	19	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	18	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	20	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	19	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	20	,	21	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	20	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	20	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	20	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	20	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	21	,	22	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	21	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	21	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	21	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	22	,	23	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	22	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	22	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	23	,	24	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	23	,	25	)));
		negativosDe2.add(new LinkedHashSet<Integer>(Arrays.asList(	24	,	25	)));

		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	17	,	18	,	20	,	21	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	20	,	21	,	22	,	12	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	11	,	17	,	21	,	22	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	8	,	10	,	14	,	25	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	3	,	4	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	12	,	16	,	25	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	7	,	10	,	13	,	15	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	6	,	9	,	19	,	24	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	5	,	14	,	15	,	16	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	6	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	8	,	13	,	16	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	4	,	5	,	10	,	12	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	18	,	22	,	23	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	17	,	20	,	23	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	3	,	11	,	18	,	23	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	16	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	8	,	12	,	15	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	5	,	13	,	25	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	2	,	4	,	7	,	14	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	12	,	13	,	14	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	16	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	9	,	10	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	4	,	15	,	25	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	7	,	8	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	3	,	14	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	18	,	22	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	13	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	4	,	23	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	15	,	19	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	12	,	25	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	11	,	20	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	5	,	13	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	2	,	10	,	16	,	12	,	24	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	2	,	21	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	17	,	18	)));
		negativosDe6.add(new LinkedHashSet<Integer>(Arrays.asList(	1	,	5	,	7	,	8	,	12	,	24	)));

	}
}
