version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_topo
    restart: always
    # Configurações de performance para o banco (Buffer Pool de 2GB)
    command: --innodb-buffer-pool-size=2G --innodb-log-file-size=512M --max-connections=200
    environment:
      MYSQL_DATABASE: topomanager
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      # O .gitignore deve ignorar esta pasta mysql_data
      - ./mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 3G

  app:
    build: .
    container_name: topomanager_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      # Injetando as configurações de memória que o seu ENTRYPOINT [sh -c] vai ler
      - JAVA_OPTS=-Xms1g -Xmx4g -XX:+UseG1GC
      # Configurações do Spring Boot
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/topomanager?rewriteBatchedStatements=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - /c/temp:/app/temp
    deploy:
      resources:
        limits:
          memory: 5G