version: '3.8'

services:
  app:
    image: srcsoftware/topomanager:1.0.0
    container_name: topomanager-prod
    restart: always
    ports:
      - "8082:8082" # Alinhado com a porta padrao do seu application.properties
    environment:
      # JVM Tuning otimizado para o seu ambiente local
      - JAVA_OPTS=-Xms2g -Xmx5g -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError
      - LOG_PATH=/app/logs
      # Garante que o console receba os logs mesmo com gravacao em arquivo ativada
      - LOGGING_PATTERN_CONSOLE=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 6.5G