# Importa apenas os logs
spring.config.import=logs.properties

spring.application.name=topomanager
server.port=${PORT:8082}

# Java 21 Performance
spring.threads.virtual.enabled=true

# Upload de Excel (50MB) - Aproveitando os 5GB de RAM
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#app.api.url=https://torneio-export-manager.onrender.com
app.api.url=http://localhost:8082