# PERMITE O ACESSO AOS VALORES DEFINIDOS NO ARQUIVOS PROPERTIES LOCAIS
spring.config.import=logs.properties

spring.application.name=topomanager
server.port=${PORT:8080}

# Habilita Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Configuracao de Upload para arquivos grandes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#app.api.url=https://torneio-export-manager.onrender.com
app.api.url=http://localhost:8080
