# ====================================================================
# 1. CONFIGURAÇÃO DE SAÍDA (PORTÁTIL)
# ====================================================================

# No Windows (Local): Criará a pasta 'logs' na raiz do seu projeto.
# No Docker (Cliente): Criará a pasta 'logs' na raiz /app.
# O uso de './' torna o caminho relativo ao diretório de execução.
logging.file.name=${LOG_PATH:./logs}/${spring.application.name}.log

# ====================================================================
# 2. ROTAÇÃO DE ARQUIVOS (MANTIDO)
# ====================================================================
logging.logback.rollingpolicy.max-file-size=50MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=5GB
logging.logback.rollingpolicy.file-name-pattern=${logging.file.name}.%d{yyyy-MM-dd}.%i.log

# ====================================================================
# 3. NÍVEIS DE LOG (TUNING SÉNIOR)
# ====================================================================
logging.level.root=INFO
logging.level.br.com.srcsoftware=DEBUG
logging.level.org.springframework=INFO

# Evita que logs de bibliotecas de terceiros inundem o console/arquivo
logging.level.org.apache.poi=WARN
logging.level.org.hibernate=WARN